import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { cookies } from "next/headers";
import jwt from "jsonwebtoken";
import { LayoutGrid, LogIn, LogOut, UserPlus } from "lucide-react";
import { logoutUser } from "./actions/authActions";
import DarkMode from "./components/Darkmode";

export const metadata: Metadata = {
  title: "나의 게시판 서비스",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value;
  const theme = cookieStore.get("theme")?.value || "light";

  type JwtUser = {
    userId: string;
    nickname: string;
    role: string;
  };

  let user: JwtUser | null = null;

  if (accessToken) {
    try {
      user = jwt.verify(accessToken, process.env.JWT_SECRET || "") as JwtUser;
    } catch {
      user = null;
    }
  }
  return (
    <html lang="ko" className={theme} style={{ colorScheme: theme }}>
      <body className="bg-bg text-fg antialiased font-sans transition-colors duration-300">
        <nav className="sticky top-0 z-40 flex items-center justify-between gap-4 border-b border-border bg-surface/80 px-6 py-4 backdrop-blur">
          <div className="flex items-center gap-6">
            <Link
              className="flex items-center gap-2 text-lg font-extrabold tracking-tight text-fg"
              href={"/"}
            >
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-accent text-accent-fg">
                <LayoutGrid size={18} />
              </span>
              게시판
            </Link>
            <Link
              className="text-sm font-medium text-muted transition-colors hover:text-fg"
              href={"/list"}
            >
              목록
            </Link>
          </div>

          <div className="flex items-center gap-3">
            <DarkMode currentTheme={theme}></DarkMode>
            {user ? (
              <div className="flex items-center gap-3">
                <span className="hidden text-sm text-muted sm:inline">
                  <span className="font-semibold text-fg">
                    {user.nickname}
                  </span>
                  님, 반가워요!
                </span>
                <form action={logoutUser}>
                  <button
                    type="submit"
                    className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-1.5 text-sm font-medium text-muted transition-colors hover:border-danger/40 hover:text-danger"
                  >
                    <LogOut size={15} />
                    로그아웃
                  </button>
                </form>
              </div>
            ) : (
              <>
                <Link
                  className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-1.5 text-sm font-medium text-muted transition-colors hover:text-fg"
                  href="/login"
                >
                  <LogIn size={15} />
                  로그인
                </Link>
                <Link
                  className="inline-flex items-center gap-1.5 rounded-lg bg-accent px-3 py-1.5 text-sm font-medium text-accent-fg transition-colors hover:bg-accent-hover"
                  href="/register"
                >
                  <UserPlus size={15} />
                  회원가입
                </Link>
              </>
            )}
          </div>
        </nav>
        <main className="mx-auto min-h-screen p-4">{children}</main>
      </body>
    </html>
  );
}
