import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "나의 게시판 서비스",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased font-sans">
        <div className="navbar">
          <Link className="navbarMenu text-3xl font-bold" href={"/"}>
            Home
          </Link>
          <Link className="navbarMenu text-lg font-medium" href={"/list"}>
            List
          </Link>
        </div>
        <main className="mx-auto min-h-screen p-4">{children}</main>
      </body>
    </html>
  );
}
